### ISSUE TITLE
Receive erros on setup

### ISSUE THREAD

**Issue by dinho-afsn** [herbecon/loopback-component-storage-mongo-gridfs#1]
Mongo DB 4
loopback 3

datasources.json
-------------------------------------------------------------------------------
  "storage": {
    "name": "gridfs",
    "connector": "loopback-component-storage-mongo-gridfs",
    "host": "127.0.0.11",
    "port": 27017,
    "database": "app",
    "username": "app",
    "password": "xxxxxxx"
  }
-------------------------------------------------------------------------------
console shows:
the options [name] is not supported
the options [connector] is not supported
the options [host] is not supported
the options [port] is not supported
the options [database] is not supported
the options [username] is not supported
the options [debug] is not supported

**Comment by clockworked247** [comment]
I get the same error.  @dinho-afsn Did you ever get this working?

**Comment by dinho-afsn** [comment]
I'm trying to this day, on my local machine it works. when I put in production every mongodb works except the gridfs.
I still haven't found the solution. I'm working on it now.

**Comment by dinho-afsn** [comment]
clockworked247

"storage": {
   "name": "gridfs",
   "connector": "loopback-component-storage-mongo-gridfs",
   "host": "hostname",
   "port": 27017,
   "database": "database",
   "username": "username", <--------------------HERE TRY CHANGE  "username" TO "user"
   "password": "password"
 }

the problem is gone but now I get permission error

statusCode: 500
name: "MongoError"
message: "not authorized on db to execute command { find: "fs.files", filter:

**Comment by herbecon** [comment]
The error has already been corrected
